// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk2j62PLFPpmK8W6GVDuUfU37kanaloIQ',
    appId: '1:787132935713:web:e503c47aba325345df7d60',
    messagingSenderId: '787132935713',
    projectId: 'login-ecc10',
    authDomain: 'login-ecc10.firebaseapp.com',
    storageBucket: 'login-ecc10.appspot.com',
    measurementId: 'G-6RC7JZD8XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtX-3xyjaxvY4hTctUVE60J37lRkGic1c',
    appId: '1:787132935713:android:14d293b5ea9a2e28df7d60',
    messagingSenderId: '787132935713',
    projectId: 'login-ecc10',
    storageBucket: 'login-ecc10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAacJzLzZ6OUyrl3cEZ8wWr23YqjxEAICE',
    appId: '1:787132935713:ios:b31173e4ff2c6d2fdf7d60',
    messagingSenderId: '787132935713',
    projectId: 'login-ecc10',
    storageBucket: 'login-ecc10.appspot.com',
    androidClientId: '787132935713-b7o8r6r8m81vs9gbhke44aha5g3a17vn.apps.googleusercontent.com',
    iosClientId: '787132935713-34eopej6qgtk9kkvrtagmqcrolku3qi1.apps.googleusercontent.com',
    iosBundleId: 'com.example.apptask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAacJzLzZ6OUyrl3cEZ8wWr23YqjxEAICE',
    appId: '1:787132935713:ios:60e88b3242a9b44cdf7d60',
    messagingSenderId: '787132935713',
    projectId: 'login-ecc10',
    storageBucket: 'login-ecc10.appspot.com',
    androidClientId: '787132935713-b7o8r6r8m81vs9gbhke44aha5g3a17vn.apps.googleusercontent.com',
    iosClientId: '787132935713-45ns280mru088tlqgptb8oq5jhe5p4e0.apps.googleusercontent.com',
    iosBundleId: 'com.example.apptask.RunnerTests',
  );
}
